config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'sessions#new'
  post '/auth/login', to: 'api/authentication#login'

  namespace :api do
    namespace :v1 do
      resources :transactions, only: %i[create]
    end
  end

  resources :transactions, only: %i[index]
  resources :sessions, only: %i[create]
  resources :merchants, only: %i[edit update destroy index]
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  before_destroy :can_destroy?, prepend: true
  include Userable

  has_many :transactions, dependent: :destroy

  private

  def can_destroy?
    return true unless transactions.any?

    errors.add(:base, I18n.t('errors.messages.can_not_delete_merchant_has_transaction'))
    throw :abort
  end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
  before_action :admin?
  before_action :current_merchant, only: %i[edit update destroy]

  # GET /merchants
  def index
    result = merchant_service.index(page: params[:page])
    @merchants = result.attributes[:merchants]
  end

  # GET /merchants/:id/edit
  def edit; end

  # PATCH/PUT /merchants/:id
  def update
    result = merchant_service.update(merchant: current_merchant, new_attrs: merchant_params)
    if result.successful?
      flash[:notice] = I18n.t('errors.messages.merchant_successfully_updated')
      redirect_to action: 'index'
    else
      flash[:notice] = result.attributes[:errors]
      redirect_to action: 'edit'
    end
  end

  # DELETE /merchants/:id
  def destroy
    result = merchant_service.destroy(merchant: current_merchant)
    flash[:notice] = if result.successful?
                       I18n.t('errors.messages.merchant_successfully_destroyed')
                     else
                       result.attributes[:errors]
                     end
    redirect_to action: 'index'
  end

  private

  def current_merchant
    @current_merchant ||= Merchant.find(params[:id])
  end

  def validate_user_permission
    head :unauthorized unless admin?
  end

  def merchant_params
    params.require(:merchant).permit(:name, :email, :status, :description)
  end

  def merchant_service
    @merchant_service ||= MerchantService.new
  end
end

app/views/merchants/_form.html.slim
.container
  center
    h2
      | Update 
      =@current_merchant.name
  = form_with model: @current_merchant do |f|
    .field.mt-2
      .row
        .col-md-8.offset-2
          = f.label :email, "Email Address"
          br
          = f.email_field :email, :class => 'form-control', :required => true
    .field.mt-2
      .row
        .col-md-8.offset-2
          = f.label :name, "Name"
          br
          = f.text_field :name, :class => 'form-control', :required => true
    .field.mt-2
      .row
        .col-md-8.offset-2
          = f.label :description, "Description"
          br
          = f.text_field :description, :class => 'form-control'
    .field.mt-2
      .row
        .col-md-8.offset-2
          = f.label :status, "Status"
          br
          = f.select(:status, options_for_select(["inactive", "active"], f.object.status), {} , { :class => 'form_control form-select' })
    .field.mt-4
      .row
        .col-md-12.offset-2
          = f.submit "Update", :class => 'btn btn-success'

app/views/merchants/_table.html.slim
table.table
  thead
    tr.text-center
      th[scope="col"]
        | ID
      th[scope="col"]
        | Name
      th[scope="col"]
        | Email
      th[scope="col"]
        | Description
      th[scope="col"]
        | Total transactions sum
      th[scope="col"]
        | Status
      th[scope="col"]
        | Created at
      th[scope="col" colspan="3"]
        | Actions
  tbody
    - @merchants.each do |merchant|
      tr.text-center
        th[scope="row"]
          =merchant[:id]
        td
          =merchant.name
        td
          =merchant.email
        td
          =merchant.description
        td
          =merchant.total_transaction_sum
        td
          =merchant.status
        td
          =merchant.created_at
        td
          = link_to 'Edit', edit_merchant_path(merchant), class: 'btn btn-success'
        td
          = link_to 'Delete', merchant_path(merchant), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger'
= will_paginate @merchants

app/views/merchants/edit.html.slim
.container
  .row.mb-5
    = render partial: 'shared/navbar'
  .row
    = render partial: 'shared/flash'
    = render partial: 'form', merchant: @current_merchant
    div

app/views/merchants/index.html.slim
.container
  .row.mb-5
    = render partial: 'shared/navbar'
  .row
    = render partial: 'shared/flash'
    = render partial: 'table'
    div